spring:
  application:
    name: id-generator

zookeeper:
  address: 127.0.0.1:2181

dubbo:
  registry:
    protocol: nacos
    address: nacos://127.0.0.1:8848
  protocol:
    name: dubbo
    port: -1
  provider:
    timeout: 10000 # 超时时间10s
    retries: 3
    loadbalance: roundrobin # 轮询